Info Section ( payments Plans , Enquire Property , Similar Project )
mohdnoorain/lander_base pull request #15
Opened 2024-12-27 15:10 UTC by Dheeru12503

I am added payments plans and enquire property .

2024-12-29 09:20 UTC, mohdnoorain commented
@Dheeru12503 
can't see **Similar projects** design here 
it should be in this task.
total 3 components in a single section

2025-01-03 20:51 UTC, Dheeru12503 commented
> @Dheeru12503 can't see **Similar projects** design here it should be in this task. total 3 components in a single section plz check the related issue for task details

done Bro

2025-01-12 19:48 UTC, mohdnoorain requested changes

2025-01-12 19:48 UTC, mohdnoorain commented on src/app/components/EnquireProperty/EnquireProperty.tsx
@Dheeru12503 change function name
why they all are gallery don't copy bluntly.
and move this function definition outside component.

2025-01-12 19:48 UTC, mohdnoorain commented on src/app/components/EnquireProperty/EnquireProperty.tsx
> +              <a key={index}  className={styles.Items}>
@Dheeru12503 
key property is used on very first element in map not on its child so 
move key property to div

2025-01-12 19:48 UTC, mohdnoorain commented on src/app/components/PaymentPlans/PaymentPlans.tsx
@Dheeru12503 
move this api call outside component

2025-01-15 07:46 UTC, Dheeru12503 commented
> @Dheeru12503 can't see **Similar projects** design here it should be in this task. total 3 components in a single section plz check the related issue for task details

I am added **similiar Project** in previous commits with "Added SimiliarProject"

2025-01-15 11:31 UTC, Dheeru12503 commented on src/app/components/EnquireProperty/EnquireProperty.tsx
> +              <a key={index}  className={styles.Items}>
Done

2025-01-15 11:41 UTC, Dheeru12503 commented on src/app/components/PaymentPlans/PaymentPlans.tsx
Done

2025-01-15 11:43 UTC, Dheeru12503 commented on src/app/components/EnquireProperty/EnquireProperty.tsx
Done

2025-01-15 11:57 UTC, mohdnoorain approved these changes

2025-01-15 11:57 UTC, merged