Page file updated
mohdnoorain/lander_base pull request #4
Opened 2024-12-18 08:43 UTC by Dheeru12503

2024-12-18 08:51 UTC, mohdnoorain commented
>###  Where is main section with image and register form 

I'm calling this Main Section


![image](https://github.com/user-attachments/assets/d1abdc35-34b0-4343-8cb6-4b4f7056c6f0)

2024-12-18 08:56 UTC, mohdnoorain commented
@Dheeru12503 
add these lines in gitignore file at bottom
```
#package-lock
package-lock.json
```

thene delete this file.

2024-12-18 09:02 UTC, mohdnoorain commented
> Also need to improve the css a little here , see the difference

not talking about background

![{B262F279-1FD0-4817-9B71-E0538E841B39}](https://github.com/user-attachments/assets/ef643f13-5dc4-437d-ab4c-3293d56ea15e)

----
![{BD4DEBBA-0610-4734-A479-6450EECC85AD}](https://github.com/user-attachments/assets/e9a638b0-97fb-4d7e-94a9-04ecdb4c483f)


- Font family 
- font size 
- spacing
- image size

2024-12-18 09:05 UTC, Dheeru12503 commented
> @Dheeru12503
> 
> > ### Where is main section with image and register form
> 
> I'm calling this Main Section
> 
> ![image](https://private-user-images.githubusercontent.com/97047245/396829944-d1abdc35-34b0-4343-8cb6-4b4f7056c6f0.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MzQ1MTI5NzUsIm5iZiI6MTczNDUxMjY3NSwicGF0aCI6Ii85NzA0NzI0NS8zOTY4Mjk5NDQtZDFhYmRjMzUtMzRiMC00MzQzLThjYjYtNGI0ZjcwNTZjNmYwLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDEyMTglMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQxMjE4VDA5MDQzNVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTgyNmRhMGI4MmZkZGQzY2ZiNDFmYTBkMDBiZmViYjdhNDM4ZjRkMTNjNThmNWU0YTg0NDVhYjVmMzg4MmQwNDMmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0In0.rcwpjYgheH2MSCvxJSvWSgGpKEwfyLLHUUInuBk5X7Y)

Done bro

2024-12-18 09:10 UTC, Dheeru12503 commented
> > Also need to improve the css a little here , see the difference
> 
> not talking about background
> 
> ![{B262F279-1FD0-4817-9B71-E0538E841B39}](https://private-user-images.githubusercontent.com/97047245/396834093-ef643f13-5dc4-437d-ab4c-3293d56ea15e.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MzQ1MTMwODksIm5iZiI6MTczNDUxMjc4OSwicGF0aCI6Ii85NzA0NzI0NS8zOTY4MzQwOTMtZWY2NDNmMTMtNWRjNC00MzdkLWFiNGMtMzI5M2Q1NmVhMTVlLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDEyMTglMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQxMjE4VDA5MDYyOVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWEyZTBkMzk4NmQ4ZDkzYzlkZDI5MWZiZTg1NDhlYTg5NmIwMTUzZmU0ZTM5YmFkM2JlZTk1ZDM0MGI2Nzc5ZDkmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0In0.TMJwfc1x0A8Fk2YuxOdIakmx3C4kMFfIs-5h1-QCNuU)
> 
> ![{BD4DEBBA-0610-4734-A479-6450EECC85AD}](https://private-user-images.githubusercontent.com/97047245/396834230-e9a638b0-97fb-4d7e-94a9-04ecdb4c483f.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MzQ1MTMwODksIm5iZiI6MTczNDUxMjc4OSwicGF0aCI6Ii85NzA0NzI0NS8zOTY4MzQyMzAtZTlhNjM4YjAtOTdmYi00ZDdlLTk0YTktMDRlY2RiNGM0ODNmLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDEyMTglMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQxMjE4VDA5MDYyOVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTRmYzc2MDA4MTU2MzQwOGRhNWQ5MTU0NjM5YmE2YjZiODA5MGRmNTM0NTdlMTk2YzNjNTNmODg4YzI2OTA2YzEmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0In0.Tcj-NGTalj4iE4k6iWDOwi9VsLTNcGRoSI7fOkzpvgw)
> 
> * Font family
> * font size
> * spacing
> * image size

which font family i should to use ?

2024-12-18 10:09 UTC, mohdnoorain commented
> which font family i should to use ? 
> 


Same as in main website.

2024-12-19 07:49 UTC, Dheeru12503 commented
> > Also need to improve the css a little here , see the difference
> 
> not talking about background
> 
> ![{B262F279-1FD0-4817-9B71-E0538E841B39}](https://private-user-images.githubusercontent.com/97047245/396834093-ef643f13-5dc4-437d-ab4c-3293d56ea15e.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MzQ1NTEzMzQsIm5iZiI6MTczNDU1MTAzNCwicGF0aCI6Ii85NzA0NzI0NS8zOTY4MzQwOTMtZWY2NDNmMTMtNWRjNC00MzdkLWFiNGMtMzI5M2Q1NmVhMTVlLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDEyMTglMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQxMjE4VDE5NDM1NFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTU3MTcwZjIzYmY0YmJhN2UxM2VkOGFhNjdlNTU3MDk2OTc4NmJmYTRiNmFmMzM4MmJhODA2MTA0ODdmZTdkZTEmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0In0.84njfus0n2ChMBzpzHYR3t1YXCIh10iVlmKHrbBu_c4)
> 
> ![{BD4DEBBA-0610-4734-A479-6450EECC85AD}](https://private-user-images.githubusercontent.com/97047245/396834230-e9a638b0-97fb-4d7e-94a9-04ecdb4c483f.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MzQ1NTEzMzQsIm5iZiI6MTczNDU1MTAzNCwicGF0aCI6Ii85NzA0NzI0NS8zOTY4MzQyMzAtZTlhNjM4YjAtOTdmYi00ZDdlLTk0YTktMDRlY2RiNGM0ODNmLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDEyMTglMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQxMjE4VDE5NDM1NFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTJmYjczNzc0MjIyNTk1YmEzYjg3MTdlMjQ3NjNkYmU3OWMxYTIzYWFjNTYyOWUxYzgzNDEyOTJhM2UxOWNlMWQmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0In0.eQGP8eGz4gdmZzU9tSujozUEvHNGXAYw5DN490-s8sU)
> 
> * Font family
> * font size
> * spacing
> * image size

Done styling is updated

2024-12-19 08:32 UTC, mohdnoorain requested changes

2024-12-19 08:32 UTC, mohdnoorain commented on src/app/section/MainSection.tsx
> +     <Header/>
@Dheeru12503 
Add main section code here.

2024-12-19 08:32 UTC, mohdnoorain commented on src/app/components/header/Header.tsx
> +export default NavBar;
@Dheeru12503 
change component name to Header.

2024-12-19 08:32 UTC, mohdnoorain commented on src/app/section/MainSection.tsx
> +export default function MainSection() {
@Dheeru12503 
don't export directly 
make it the same as in header
```
const ComponentName: React.FC = () => {
}

export default ComponentName
```

2024-12-19 08:32 UTC, mohdnoorain commented on src/app/section/MainSection.tsx
> +     <Header/>
@Dheeru12503 
is this done ?

2024-12-19 08:32 UTC, mohdnoorain commented on src/app/section/MainSection.tsx
> +export default function MainSection() {
@Dheeru12503 
and this ?

2024-12-19 08:39 UTC, Dheeru12503 commented on src/app/section/MainSection.tsx
> +     <Header/>
Done

2024-12-19 08:58 UTC, Dheeru12503 commented on src/app/section/MainSection.tsx
> +export default function MainSection() {
done

2024-12-19 09:03 UTC, mohdnoorain requested changes

2024-12-19 09:03 UTC, mohdnoorain commented on src/app/components/heroSection/HeroSection.tsx
@Dheeru12503 
Add max width in header and main section

2024-12-19 09:03 UTC, mohdnoorain commented on src/app/components/signUpForm/SignUpForm.tsx
@Dheeru12503 
change component name to EnquiryForm

2024-12-19 09:03 UTC, mohdnoorain commented on src/app/components/signUpForm/SignUpForm.tsx
add country dropdown

2024-12-20 06:11 UTC, Dheeru12503 commented on src/app/components/heroSection/HeroSection.tsx
Done

2024-12-20 06:37 UTC, Dheeru12503 commented on src/app/components/signUpForm/SignUpForm.tsx
done

2024-12-21 16:08 UTC, mohdnoorain requested changes

2024-12-21 16:08 UTC, mohdnoorain commented on src/app/layout.tsx
>        <link
@Dheeru12503 
wrap this link in head tag.
It's giving error on consoles

2024-12-22 10:02 UTC, mohdnoorain approved these changes

2024-12-22 10:03 UTC, merged